name: Build Custom Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Nginx Image
        run: docker pull nginx:alpine

      - name: Build Custom Docker Image
        run: |
          docker build -t anandriasyan/custom-nginx-image:latest  Exam/.github/workflows/
          docker images


